default: &default
  host: localhost
  username: root
  password: root
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: hellobar_development

test:
  <<: *default
  database: hellobar_test

production:
  <<: *default
  database: hellobar_production

wordpress_development:
  <<: *default
  database: hellobar_wordpress_development

benchmark:
  <<: *default
  database: hellobar_production
