default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: new_hellobar_development

test:
  <<: *default
  database: hellobar_test

production:
  <<: *default
  database: hellobar_production
  username: hellobar
  password: <%= ENV['HELLOBAR_DATABASE_PASSWORD'] %>
