# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  deliver_emails: true

development:
  <<: *defaults

  secret_key_base: c7c7169427194da0b5b2064de34174b6979f57bc7b808f6b50335cf0b6e1de1e5e8d302b99a1e850660e2fc07effbeedae53c3084718200dfe9b911762c40838

test:
  <<: *defaults

  deliver_emails: false
  secret_key_base: ad07d3c6c681c72c86770d066b4c5e9c14db83c2b1b49323bf142ab51804c3cc9afd469d5cb9c629605da46f714002ea30adf3623b3ef1c72cb4bf473cf41508
